version: "3.7"

services:
  bot_control_panel:
    build: .
    restart: unless-stopped
    container_name: bot_control_panel
    env_file: .env
    depends_on:
      - postgres_bot
    ports:
      - 8000:8000
    command: "--development"
    networks:
      - ds_net
    volumes:
      - ./src/migrations:/controlpanel/migrations
    develop:
      watch:
        - action: sync
          path: ./src/web/
          target: /controlpanel/web/
          ignore:
            - "**/__pycache__/"

        - action: rebuild
          path: ./Dockerfile

        - action: sync+restart
          path: ./src/scripts/entrypoint.sh
          target: /controlpanel/entrypoint.sh

        - action: rebuild
          path: ./src/requirements.txt

  postgres_bot:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres_bot
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ds_net

networks:
  ds_net:
    driver: bridge
